swagger: '2.0'
info:
  description: 'ポケモンに関する情報を提供する API'
  version: 1.0.0
  title: ポケモン API
  # termsOfService: 'http://localhost/pokemon-api/terms'
  contact:
    email: noriyuki.shimizu0612@gmail.com
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8003
basePath: /pokemon-api/v1
tags:
  - name: Pokemon
    description: ポケモン情報に関する API
#     externalDocs:
#       description: Find out more
#       url: 'https://github.com/pokemon-picture-book/pokemon.json'
  - name: GameVersionGroup
    description: ゲームバージョングループ情報に関する API
  - name: Region
    description: 地域情報に関する API
  - name: Language
    description: 言語情報に関する API
schemes:
  - http
  - https
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
paths:
  /pokemons:
    get:
      tags:
        - Pokemon
      parameters:
      - name: lang
        in: query
        description: 言語 (英語 - en / 日本語 - ja-Hrkt)
        type: string
      - name: game
        in: query
        description:
          ゲームバージョン
          (rgby / gsc / rse / frlg / dp / pt / hgss / bw / c / x / bw2 / xy / oras / sm / usum)
        type: string
      - name: regions
        in: query
        description: 地方 (kanto / johto / hoenn / sinnoh / unova / kalos / alola)
        type: array
        items:
          type: string
      summary: ポケモン一覧取得
      description: |-
        ## 詳細
        パラメータに紐づくポケモン情報一覧を取得します
      operationId: findAllPokemons
      produces:
        - application/json
      responses:
        200:
          description: 通信が正常に成功した場合
          schema:
            type: array
            items:
              $ref: '#/definitions/PokemonListResponse'
        204:
          description: データが見つからなかった場合
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'No Content!'
        400:
          description: 不正なリクエストをした場合
          schema:
            $ref: '#/definitions/QueryError'
  /game-version-groups:
    get:
      tags:
        - GameVersionGroup
      parameters:
      - name: lang
        in: query
        description: 言語 (英語 - en / 日本語 - ja-Hrkt)
        type: string
      - name: supported
        in: query
        description: サポートされてるか（Yes - true / No - false）
        type: boolean
      summary: ゲームバージョングループ一覧取得
      description: |-
        ## 詳細
        ゲームバージョングループ情報一覧を取得します
      operationId: findAllGameVerisionGroups
      produces:
        - application/json
      responses:
        200:
          description: 通信が正常に成功した場合
          schema:
            type: array
            items:
              $ref: '#/definitions/GameVersionGroupListResponse'
        204:
          description: データが見つからなかった場合
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'No Content!'
        400:
          description: 不正なリクエストをした場合
          schema:
            $ref: '#/definitions/QueryError'
  /regions:
    get:
      tags:
        - Region
      parameters:
      - name: lang
        in: query
        description: 言語 (英語 - en / 日本語 - ja-Hrkt)
        type: string
      summary: 地域一覧取得
      description: |-
        ## 詳細
        地域情報一覧を取得します
      operationId: findAllRegions
      produces:
        - application/json
      responses:
        200:
          description: 通信が正常に成功した場合
          schema:
            type: array
            items:
              $ref: '#/definitions/RegionListResponse'
        204:
          description: データが見つからなかった場合
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'No Content!'
        400:
          description: 不正なリクエストをした場合
          schema:
            $ref: '#/definitions/QueryError'
  /languages:
    get:
      tags:
        - Language
      summary: 言語一覧取得
      description: |-
        ## 詳細
        言語情報一覧を取得します
        言語名の昇順でデータを取得します
      operationId: findAllLanguages
      produces:
        - application/json
      responses:
        200:
          description: 通信が正常に成功した場合
          schema:
            type: array
            items:
              $ref: '#/definitions/LanguageListResponse'
        204:
          description: データが見つからなかった場合（運用上 204 は起こり得ない）
          schema:
            type: object
            properties:
              message:
                type: string
                example: 'No Content!'
definitions:
  PokemonListResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 25
      imageColor:
        type: string
        example: 'yellow'
      name:
        type: string
        example: 'ピカチュウ'
      gameImagePath:
        type: object
        properties:
          mainPath:
            type: string
            example: '/25/rgby/25.png'
          otherPaths:
            type: array
            items:
              type: string
              example:
                - '/25/icon/1/1.gif'
      imagePaths:
        type: array
        items:
          type: string
          example:
            - '/25/footmark/25.png'
            - '/25/overworld/25-1.gif'
      types:
        type: array
        items:
          type: object
          properties:
            code:
              type: string
              example: 'electric'
            name:
              type: string
              example: 'でんき'
  GameVersionGroupListResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      alias:
        type: string
        example: 'rgby'
      name:
        type: string
        example: '赤/緑/ピカチュウ'
      relatedRegions:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 1
            name:
              type: string
              example: 'kanto'
  RegionListResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: 'kanto'
      displayName:
        type: string
        example: 'カントー地方'
      relatedGameVersionGroups:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              example: 1
            alias:
              type: string
              example: 'rgby'
  LanguageListResponse:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      name:
        type: string
        example: 'ja-Hrkt'
      labelName:
        type: string
        example: '日本語'
  QueryError:
    type: object
    properties:
      errors:
        type: array
        items:
          type: object
          properties:
            value:
              type: string
              example: ja-Hrktu
            msg:
              type: string
              example: Select en or ja-Hrkt as the \"lang\"
            param:
              type: string
              example: lang
            location:
              type: string
              example: query