swagger: '2.0'
info:
  description: 'ポケモン情報取得に関する API.'
  version: 1.0.0
  title: ポケモン情報取得 API
  # termsOfService: 'http://localhost/pokemon-api/terms'
  contact:
    email: noriyuki.shimizu0612@gmail.com
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:3001
basePath: /pokemon-api/v1
tags:
  - name: pokemons
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'https://github.com/pokemon-picture-book/pokemon.json'
schemes:
  - http
  - https
paths:
  /pokemons:
    get:
      tags:
        - pokemons
      summary: Find All Pokemons
      description: ポケモン情報を全件取得します.
      operationId: findAllPokemons
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Pokemons'
definitions:
  Pokemons:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 25
      name:
        type: string
        example: 'ピカチュウ'
      code:
        type: string
        example: 'Pikachu'
      generationNo:
        type: integer
        format: int64
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
    xml:
      name: Pokemons
  # ApiResponse:
  #   type: object
  #   properties:
  #     code:
  #       type: integer
  #       format: int32
  #     type:
  #       type: string
  #     message:
  #       type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
