import EvolutionEntity from '@/domain/entity/Evolution.entity';
import FlavorTextEntryEntity from '@/domain/entity/FlavorTextEntry.entity';
import GameVersionEntity from '@/domain/entity/GameVersion.entity';
import GameVersionGroupEntity from '@/domain/entity/GameVersionGroup.entity';
import GameVersionNameEntity from '@/domain/entity/GameVersionName.entity';
import GeneraEntity from '@/domain/entity/Genera.entity';
import LanguageEntity from '@/domain/entity/Language.entity';
import PokemonEntity from '@/domain/entity/Pokemon.entity';
import PokemonEvolutionEntity from '@/domain/entity/PokemonEvolution.entity';
import PokemonGameImageEntity from '@/domain/entity/PokemonGameImage.entity';
import PokemonImageEntity from '@/domain/entity/PokemonImage.entity';
import PokemonNameEntity from '@/domain/entity/PokemonName.entity';
import PokemonTypeEntity from '@/domain/entity/PokemonType.entity';
import RegionEntity from '@/domain/entity/Region.entity';
import RegionNameEntity from '@/domain/entity/RegionName.entity';
import StatusEntity from '@/domain/entity/Status.entity';
import TypeEntity from '@/domain/entity/Type.entity';
import TypeNameEntity from '@/domain/entity/TypeName.entity';

declare type Evolution = InstanceType<typeof EvolutionEntity>;
declare type FlavorTextEntry = InstanceType<typeof FlavorTextEntryEntity>;
declare type GameVersion = InstanceType<typeof GameVersionEntity>;
declare type GameVersionGroup = InstanceType<typeof GameVersionGroupEntity>;
declare type GameVersionName = InstanceType<typeof GameVersionNameEntity>;
declare type Genera = InstanceType<typeof GeneraEntity>;
declare type Language = InstanceType<typeof LanguageEntity>;
declare type Pokemon = InstanceType<typeof PokemonEntity>;
declare type PokemonEvolution = InstanceType<typeof PokemonEvolutionEntity>;
declare type PokemonGameImage = InstanceType<typeof PokemonGameImageEntity>;
declare type PokemonImage = InstanceType<typeof PokemonImageEntity>;
declare type PokemonName = InstanceType<typeof PokemonNameEntity>;
declare type PokemonType = InstanceType<typeof PokemonTypeEntity>;
declare type Region = InstanceType<typeof RegionEntity>;
declare type RegionName = InstanceType<typeof RegionNameEntity>;
declare type Status = InstanceType<typeof StatusEntity>;
declare type Type = InstanceType<typeof TypeEntity>;
declare type TypeName = InstanceType<typeof TypeNameEntity>;
