import EvolutionEntity from './Evolution.entity';
import FlavorTextEntryEntity from './FlavorTextEntry.entity';
import GameVersionEntity from './GameVersion.entity';
import GameVersionGroupEntity from './GameVersionGroup.entity';
import GameVersionNameEntity from './GameVersionName.entity';
import GeneraEntity from './Genera.entity';
import LanguageEntity from './Language.entity';
import PokemonEntity from './Pokemon.entity';
import PokemonEvolutionEntity from './PokemonEvolution.entity';
import PokemonGameImageEntity from './PokemonGameImage.entity';
import PokemonImageEntity from './PokemonImage.entity';
import PokemonNameEntity from './PokemonName.entity';
import PokemonTypeEntity from './PokemonType.entity';
import RegionEntity from './Region.entity';
import RegionNameEntity from './RegionName.entity';
import StatusEntity from './Status.entity';
import TypeEntity from './Type.entity';
import TypeNameEntity from './TypeName.entity';

declare type Evolution = InstanceType<typeof EvolutionEntity>;
declare type FlavorTextEntry = InstanceType<typeof FlavorTextEntryEntity>;
declare type GameVersion = InstanceType<typeof GameVersionEntity>;
declare type GameVersionGroup = InstanceType<typeof GameVersionGroupEntity>;
declare type GameVersionName = InstanceType<typeof GameVersionNameEntity>;
declare type Genera = InstanceType<typeof GeneraEntity>;
declare type Language = InstanceType<typeof LanguageEntity>;
declare type Pokemon = InstanceType<typeof PokemonEntity>;
declare type PokemonEvolution = InstanceType<typeof PokemonEvolutionEntity>;
declare type PokemonGameImage = InstanceType<typeof PokemonGameImageEntity>;
declare type PokemonImage = InstanceType<typeof PokemonImageEntity>;
declare type PokemonName = InstanceType<typeof PokemonNameEntity>;
declare type PokemonType = InstanceType<typeof PokemonTypeEntity>;
declare type Region = InstanceType<typeof RegionEntity>;
declare type RegionName = InstanceType<typeof RegionNameEntity>;
declare type Status = InstanceType<typeof StatusEntity>;
declare type Type = InstanceType<typeof TypeEntity>;
declare type TypeName = InstanceType<typeof TypeNameEntity>;
