pokemon:
  api:
    url: https://pokeapi.co/api/v2
  data:
    git:
      path: https://raw.githubusercontent.com/pokemon-picture-book/pokemon.json/master
  generation:
    first: 151
    second: 251
    third: 386
    fourth: 493
    fifth: 649
    sixth: 721
